### 씨애랑 3주차 강의

In [ ]:
pip install numpy

Numpy 의 핵심 기능 중 하나는 n-차원 배열인 ndarry 객체

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print("생성한 배열 : ", arr)

생성한 배열 :  [1 2 3 4 5]


In [4]:
print("배열의 차원: ", arr.ndim)
print("배열의 모양: ", arr.shape)
print("배열의 크기: ", arr.size)
print("배열의 데이터 타입: ", arr.dtype)

배열의 차원:  1
배열의 모양:  (5,)
배열의 크기:  5
배열의 데이터 타입:  int64


### Numpy 연산 및 함수

In [5]:
# Numpy 배열 생성
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 기본적인 사칙연산
print("덧셈: ", np.add(arr1, arr2))
print("뺄셈: ", np.subtract(arr1, arr2))
print("곱셈: ", np.multiply(arr1, arr2))
print("나눗셈: ", np.divide(arr1, arr2))

print("제곱근: ", np.sqrt(arr1))
print("로그: ", np.log(arr1))

덧셈:  [5 7 9]
뺄셈:  [-3 -3 -3]
곱셈:  [ 4 10 18]
나눗셈:  [0.25 0.4  0.5 ]
제곱근:  [1.         1.41421356 1.73205081]
로그:  [0.         0.69314718 1.09861229]


In [6]:
print("합계: ", np.sum(arr1))
print("최소값: ", np.min(arr1))
print("최대값: ", np.max(arr1))
print("평균값: ", np.mean(arr1))

합계:  6
최소값:  1
최대값:  3
평균값:  2.0


### Numpy  배열 변형, 결합, 분할

In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("원본 배열:\n", arr)

# reshape 함수를 사용한 배열 변형
reshaped_arr = arr.reshape(3, 2)
print("\nreshape를 이용한 배열 변형:\n", reshaped_arr)

# ravel 함수를 사용한 1차원 배열 변환
flattened_arr = arr.ravel()
print("\nravel을 이용한 1차원 배열 변환:\n", flattened_arr)

원본 배열:
 [[1 2 3]
 [4 5 6]]

reshape를 이용한 배열 변형:
 [[1 2]
 [3 4]
 [5 6]]

ravel을 이용한 1차원 배열 변환:
 [1 2 3 4 5 6]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# vstack을 이용한 배열 결합
vstacked_arr = np.vstack((arr1, arr2))
print("\nvstack을 이용한 배열 결합:\n", vstacked_arr)

# hstack을 이용한 배열 결합
hstacked_arr = np.hstack((arr1, arr2))
print("\nhstack을 이용한 배열 결합:\n", hstacked_arr)


vstack을 이용한 배열 결합:
 [[1 2 3]
 [4 5 6]]

hstack을 이용한 배열 결합:
 [1 2 3 4 5 6]


In [9]:
arr = np.arange(9).reshape(3, 3)
print("\n원본 배열:\n", arr)

# hsplit을 이용한 배열 분할
splitted_arr = np.hsplit(arr, 3)
print("\nhsplit을 이용한 배열 분할:")
for sub_arr in splitted_arr:
    print(sub_arr)


원본 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

hsplit을 이용한 배열 분할:
[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]


### Numpy 브로드캐스팅, 정렬, 검색, 집계 함수

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3]).reshape(3, 1)

# 브로드캐스팅을 이용한 연산
print("\n브로드캐스팅을 이용한 연산:\n", arr1 * arr2)


브로드캐스팅을 이용한 연산:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

# np.sort를 이용한 정렬
sorted_arr = np.sort(arr)
print("\nnp.sort를 이용한 정렬:\n", sorted_arr)

# np.argsort를 이용한 정렬
sorted_index = np.argsort(arr)
print("\nnp.argsort를 이용한 정렬:\n", sorted_index)


np.sort를 이용한 정렬:
 [1 2 3 4 5 6 7 8]

np.argsort를 이용한 정렬:
 [1 0 3 5 2 6 4 7]


In [12]:
# np.where를 이용
result = np.where(arr > 4)
print("\nnp.where를 이용한 검색:\n", result)


np.where를 이용한 검색:
 (array([2, 4, 6, 7]),)


In [13]:
print("\n합계: ", np.sum(arr))
print("최소값: ", np.min(arr))
print("최대값: ", np.max(arr))
print("평균값: ", np.mean(arr))


합계:  36
최소값:  1
최대값:  8
평균값:  4.5
